// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYM2NV3oWXheGDYynQTwH9p7TtkGYVSuU',
    appId: '1:485591531562:web:22353998c82662a2610353',
    messagingSenderId: '485591531562',
    projectId: 'my-gym-login',
    authDomain: 'my-gym-login.firebaseapp.com',
    storageBucket: 'my-gym-login.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvHPxJN1sXsSrJW9hrV0-93tE_3_2pe2A',
    appId: '1:485591531562:android:fc72085396967c89610353',
    messagingSenderId: '485591531562',
    projectId: 'my-gym-login',
    storageBucket: 'my-gym-login.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6MLGmMsA2wMPdl30bbnE2qNOCeCrUSQo',
    appId: '1:485591531562:ios:5ae21150a36f9bf0610353',
    messagingSenderId: '485591531562',
    projectId: 'my-gym-login',
    storageBucket: 'my-gym-login.firebasestorage.app',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6MLGmMsA2wMPdl30bbnE2qNOCeCrUSQo',
    appId: '1:485591531562:ios:5ae21150a36f9bf0610353',
    messagingSenderId: '485591531562',
    projectId: 'my-gym-login',
    storageBucket: 'my-gym-login.firebasestorage.app',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYM2NV3oWXheGDYynQTwH9p7TtkGYVSuU',
    appId: '1:485591531562:web:855cf50610be9905610353',
    messagingSenderId: '485591531562',
    projectId: 'my-gym-login',
    authDomain: 'my-gym-login.firebaseapp.com',
    storageBucket: 'my-gym-login.firebasestorage.app',
  );
}
